# Generated by Django 5.1.4 on 2024-12-28 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('eml_id', models.CharField(max_length=50, unique=True)),
                ('acc_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('acc_nme', models.CharField(max_length=255)),
                ('acc_sec_tkn', models.TextField()),
            ],
        ),
    ]
